security:
    providers:
        ezpublish:
            id: ezpublish.security.user_provider
#        in_memory:
#            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        ezpublish_rest:
#            pattern: ^/api/ezp/v2
#            stateless: true
#            ezpublish_http_basic:
#                realm: eZ Publish REST API

        ezpublish_front:
            pattern: ^/
            anonymous: ~
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                login_path:  /login
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: crevillo.ezsocialloginbundle.oauth_aware.user_provider.service
            ezpublish_rest_session: ~
            form_login:
                require_previous_session: false
            logout: ~

        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
